import React from 'react';

const Apy = () => {
  return (
    <div className="p-4">
      <h1 className="text-2xl font-bold mb-4 text-center">APY</h1>
      <p className="text-white/60 text-center mb-4 ">The APY page provides visual insights into the annual percentage yield (APY) of various stake pool tokens, expressed in both HEX and USD terms. This page is designed to help users understand the projected growth of their investments over time based on the principle and yield generated by each token. By adjusting the initial investment input, users can see how the value evolves year over year, allowing for strategic planning and comparison of token performance.</p>
      <p className="text-white/60 text-2xl text-center">data coming soon...</p>
    </div>
  );
};

export default Apy;